In [2]:
import numpy as np

from sklearn import datasets
import pandas as pd


iris = datasets.load_iris()


data = np.asarray(iris.data)
target = np.asarray(iris.target)
feature_names = np.asarray(iris.feature_names) 
target_names = np.asarray(iris.target_names)
 
print(data[0:5])
print(target[0:5])
print(feature_names[0:4])
print(target_names)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [3]:
target = target.reshape(150,1)


arr = np.hstack(([data, target]))


In [189]:
print(arr[:5])




[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [282]:
print(new_array)

None


In [195]:
# Mask array..para tener 3 arrays por separado segun especie...por si acaso

mask = (arr[:,4]==0)
mask1 =(arr[:,4]==1)
mask2 =(arr[:,4]==2)

Setosa = arr[mask]
Versicolor =arr[mask1] 
Virginica = arr[mask2]



EX3 Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length
(cm)").
Mostra els resultats amb dos decimals.


In [28]:
longitud_sèpal = (arr[:,0]) 

longitud_pètal = (arr[:,2])

Mitjana_sèpal = round(longitud_sèpal.mean(), 2)
Mitjana_pètal = round(longitud_pètal.mean(), 2)

Desviació_estandard_sèpal = round(longitud_sèpal.std(),2)
Desviació_estandard_pètal = round(longitud_pètal.std(),2)



print("Per sèpal la Mitjana i la Desviació_estàndard son ", Mitjana_sèpal, Desviació_estandard_sèpal )
print("Per pètal la Mitjana i la Desviació_estàndard son " , Mitjana_pètal, Desviació_estandard_pètal )




Per sèpal la Mitjana i la Desviació_estàndard son  5.84 0.83
Per pètal la Mitjana i la Desviació_estàndard son  3.76 1.76


- Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.


In [191]:
import random
new_array =np.array( random.choices(arr,k =20))
new_array

array([[7.1, 3. , 5.9, 2.1, 2. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [5.1, 3.5, 1.4, 0.2, 0. ],
       [5.5, 4.2, 1.4, 0.2, 0. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [5.5, 2.6, 4.4, 1.2, 1. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5.1, 3.5, 1.4, 0.2, 0. ]])

- Exercici 5
Crea una matriu que mostri:
• La mitjana de cada característica per espècie.
• La desviació estàndard de cada característica per espècie.

In [90]:
import numpy as np

matriu_mitjana = np.zeros((3, 4))


for i in range(3):
    for j in range(4):
        matriu_mitjana[i][j] = round(np.mean(arr[:,int(j)], where = arr[:, 4]== i),2)
        
        
print(matriu_mitjana)
        

[[5.01 3.43 1.46 0.25]
 [5.94 2.77 4.26 1.33]
 [6.59 2.97 5.55 2.03]]


In [89]:
import numpy as np

std_matrix = np.zeros((3, 4))
for i in range(3):
    for j in range(4):
        std_matrix[i][j] = round(np.std(arr[:,int(j)], where = arr[:, 4] == i),2)
        
print(std_matrix)



[[0.35 0.38 0.17 0.1 ]
 [0.51 0.31 0.47 0.2 ]
 [0.63 0.32 0.55 0.27]]


- Exercici 6
• Calcula la quantitat de mostres per espècie. 

In [221]:
values,counts = np.unique(arr[:,4], return_counts=True)

counts



array([50, 50, 50], dtype=int64)

• Exercici 6 bis : Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [228]:
Valor_maxim_mitjana = np.max(matriu_mitjana[:,0])
print (round((Valor_maxim_mitjana),2))

a = np.argmax(matriu_mitjana[:,0])

#k = arr[np.argmax(matriu_mitjana[:,0],4)
Especie_Max = (arr[ np.argmax(arr[:,0]),4])


6.59








EX 7 Calcula la matriu de Correlació

 

In [116]:
z = np.corrcoef(arr, rowvar=False)
z

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.95654733],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 



In [161]:
for i in range(3):
    Mask  = np.where((arr[:,2] > matriu_mitjana[0,i]))
    
    matriu_filtrada = arr[Mask]
    print(matriu_filtrada)
    

[[6.  2.7 5.1 1.6 1. ]
 [6.3 3.3 6.  2.5 2. ]
 [5.8 2.7 5.1 1.9 2. ]
 [7.1 3.  5.9 2.1 2. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.5 3.  5.8 2.2 2. ]
 [7.6 3.  6.6 2.1 2. ]
 [7.3 2.9 6.3 1.8 2. ]
 [6.7 2.5 5.8 1.8 2. ]
 [7.2 3.6 6.1 2.5 2. ]
 [6.5 3.2 5.1 2.  2. ]
 [6.4 2.7 5.3 1.9 2. ]
 [6.8 3.  5.5 2.1 2. ]
 [5.8 2.8 5.1 2.4 2. ]
 [6.4 3.2 5.3 2.3 2. ]
 [6.5 3.  5.5 1.8 2. ]
 [7.7 3.8 6.7 2.2 2. ]
 [7.7 2.6 6.9 2.3 2. ]
 [6.9 3.2 5.7 2.3 2. ]
 [7.7 2.8 6.7 2.  2. ]
 [6.7 3.3 5.7 2.1 2. ]
 [7.2 3.2 6.  1.8 2. ]
 [6.4 2.8 5.6 2.1 2. ]
 [7.2 3.  5.8 1.6 2. ]
 [7.4 2.8 6.1 1.9 2. ]
 [7.9 3.8 6.4 2.  2. ]
 [6.4 2.8 5.6 2.2 2. ]
 [6.3 2.8 5.1 1.5 2. ]
 [6.1 2.6 5.6 1.4 2. ]
 [7.7 3.  6.1 2.3 2. ]
 [6.3 3.4 5.6 2.4 2. ]
 [6.4 3.1 5.5 1.8 2. ]
 [6.9 3.1 5.4 2.1 2. ]
 [6.7 3.1 5.6 2.4 2. ]
 [6.9 3.1 5.1 2.3 2. ]
 [5.8 2.7 5.1 1.9 2. ]
 [6.8 3.2 5.9 2.3 2. ]
 [6.7 3.3 5.7 2.5 2. ]
 [6.7 3.  5.2 2.3 2. ]
 [6.5 3.  5.2 2.  2. ]
 [6.2 3.4 5.4 2.3 2. ]
 [5.9 3.  5.1 1.8 2. ]]
[[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 

 Troba la mostra amb els pètals més grans.


In [239]:

Especie_Max = (arr[ np.argmax(arr[:,0]),4])
           
Especie_Max

2.0

 Exercici 8
Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [236]:
Max_dev_Sepal =  np.argmax(std_matrix[:,0])
Max_dev_Petal =  np.argmax(std_matrix[:,2])

Max_dev_Sepal


2

In [237]:
Max_dev_Petal

2